language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- nightly
env:
- CYTHON_VERSION=0.19
- CYTHON_VERSION=
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache
install:
- mkdir deps
- wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz -O deps/afl.tar.gz
- tar -xvzf deps/afl.tar.gz -C deps/
- make -C deps/afl-*/ install PREFIX="$PWD/deps"
- pip install --upgrade pip
- pip install --verbose cython${CYTHON_VERSION:+==$CYTHON_VERSION}
- pip install docutils
- pip install pygments
script:
- python setup.py install
- export PATH="$PWD/deps/bin:$PATH"
- nosetests --verbose
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || find -name "*.rst" | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
