dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
env:
- CYTHON_VERSION=0.19
- CYTHON_VERSION=
matrix:
  exclude:
  - python: "3.7-dev"
    env: CYTHON_VERSION=0.19
cache: pip
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 2.6 ] ||
  \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- mkdir deps
- wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz -O deps/afl.tar.gz
- tar -xvzf deps/afl.tar.gz -C deps/
- make -C deps/afl-*/ install PREFIX="$PWD/deps"
- if [ "$TRAVIS_PYTHON_VERSION" = 3.2 ] && [ -z "$CYTHON_VERSION" ]; then CYTHON_VERSION=0.26.1; fi
- pip install --verbose cython${CYTHON_VERSION:+==$CYTHON_VERSION}
- pip install pydiatra pyflakes
- $no_pylint || pip install pylint
- pip install docutils pygments
script:
- python setup.py install
- export PATH="$PWD/deps/bin:$PATH"
- nosetests --verbose
- python -m pydiatra .
- pyflakes .
- $no_pylint || private/run-pylint
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || private/check-rst
- curl -fsS https://pypi.python.org/simple/afl/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
